const TCS_API_BASE='https://marketplace-c3wq.onrender.com';
function apiUrl(p){return TCS_API_BASE+p}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(path,opt={}){const r=await fetch(apiUrl(path),opt);const x=await r.json().catch(()=>({error:'Invalid server response'}));if(!r.ok)throw Error(x.error||'Request failed');return x}
function statusOf(x){return x.approvalStatus==='pending'?'pending':(x.status||x.approvalStatus||'draft')}
function card(x){const img=x.coverImage?`<img class="listing-image" src="${apiUrl(x.coverImage)}" alt="${esc(x.title)}">`:'<div class="mock-img">No photo</div>';return `<article class="card admin-manage-card" data-status="${esc(statusOf(x))}">${img}<div class="admin-card-head"><span class="status ${esc(statusOf(x))}">${esc(statusOf(x))}</span><small>${esc(x.id)}</small></div><label>Advert title<input id="title_${x.id}" value="${esc(x.title)}" maxlength="120"></label><div class="split"><label>Price<input id="price_${x.id}" type="number" min="0" step="0.01" value="${Number(x.price||0)}"></label><label>Price type<select id="priceType_${x.id}">${['Fixed','From','Negotiable','Price on Request'].map(v=>`<option ${x.priceType===v?'selected':''}>${v}</option>`).join('')}</select></label></div><label>Description<textarea id="description_${x.id}" maxlength="3000">${esc(x.description)}</textarea></label><div class="split"><label>Town<input id="town_${x.id}" value="${esc(x.town)}"></label><label>Province<input id="province_${x.id}" value="${esc(x.province)}"></label></div><p class="small"><b>Seller:</b> ${esc(x.sellerId||'Not supplied')}<br><b>Phone:</b> ${esc(x.phone||'')} · <b>WhatsApp:</b> ${esc(x.whatsapp||'')}</p><div class="listing-actions"><button onclick="saveAdvert('${x.id}')">Save Changes</button>${x.approvalStatus==='pending'?`<button onclick="approveAdvert('${x.id}')">Approve</button>`:''}<button class="btn warn" onclick="setAdvertState('${x.id}','${x.status==='active'?'suspend':'activate'}')">${x.status==='active'?'Suspend':'Make Active'}</button><button class="btn danger" onclick="deleteAdvert('${x.id}', '${esc(x.title).replace(/'/g,'&#39;')}')">Delete Permanently</button></div><div id="result_${x.id}" class="small"></div></article>`}
let allRows=[];
async function loadAllAdminAdverts(){const el=document.getElementById('allAdminAdverts');el.innerHTML='<div class="box">Loading all adverts...</div>';try{allRows=await api('/api/listings/admin/all',{headers:{'x-demo-user':'u_admin_1'}});renderRows()}catch(e){el.innerHTML=`<div class="notice">${esc(e.message)}</div>`}}
function renderRows(){const f=document.getElementById('adminStatusFilter').value;const rows=f?allRows.filter(x=>statusOf(x)===f):allRows;document.getElementById('adminAdvertCount').textContent=`${rows.length} advert${rows.length===1?'':'s'}`;document.getElementById('allAdminAdverts').innerHTML=rows.length?rows.map(card).join(''):'<div class="box">No adverts found for this filter.</div>'}
async function saveAdvert(id){const out=document.getElementById('result_'+id);out.textContent='Saving...';try{await api('/api/listings/admin/'+id,{method:'PATCH',headers:{'Content-Type':'application/json','x-demo-user':'u_admin_1'},body:JSON.stringify({title:document.getElementById('title_'+id).value,price:document.getElementById('price_'+id).value,priceType:document.getElementById('priceType_'+id).value,description:document.getElementById('description_'+id).value,town:document.getElementById('town_'+id).value,province:document.getElementById('province_'+id).value})});out.innerHTML='<span class="status approved">Changes saved</span>';await loadAllAdminAdverts()}catch(e){out.textContent=e.message}}
async function approveAdvert(id){await api('/api/listings/admin/'+id+'/approve',{method:'POST',headers:{'Content-Type':'application/json','x-demo-user':'u_admin_1'},body:'{}'});await loadAllAdminAdverts()}
async function setAdvertState(id,action){await api('/api/marketplace-live/admin/listing/'+id+'/action',{method:'POST',headers:{'Content-Type':'application/json','x-demo-user':'u_admin_1'},body:JSON.stringify({action})});await loadAllAdminAdverts()}
async function deleteAdvert(id,title){if(!confirm(`Permanently delete "${title}"? This also removes its uploaded photos and cannot be undone.`))return;if(!confirm('Final confirmation: permanently delete this advert?'))return;await api('/api/listings/admin/'+id,{method:'DELETE',headers:{'x-demo-user':'u_admin_1'}});await loadAllAdminAdverts()}
document.getElementById('adminStatusFilter').addEventListener('change',renderRows);addEventListener('DOMContentLoaded',loadAllAdminAdverts);