const express=require('express');
const config=require('./src/config');
const {parseCookies,setSecurityHeaders,rateLimit}=require('./src/security');
const neonDb=require('./src/neonDb');
const neonStorage=require('./src/neonStorage');
const app=express();
const allowedOrigins=new Set(['https://marketplace.tcstowing.co.za','https://www.marketplace.tcstowing.co.za','http://localhost:3000']);
app.use((req,res,next)=>{const origin=req.headers.origin;if(origin&&allowedOrigins.has(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Demo-User');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS')}if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.set('trust proxy',1);app.use(parseCookies);app.use(setSecurityHeaders);app.use(rateLimit());app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));
app.get('/api/health',async(req,res)=>{try{const database=await neonDb.health();let storage;try{storage=await neonStorage.health()}catch(e){storage={configured:neonStorage.configured,ok:false,error:e.message}}res.json({ok:true,service:'tcs-marketplace',build:'46-neon-persistent-marketplace',database:{ok:true,name:database.database},storage})}catch(e){res.status(503).json({ok:false,service:'tcs-marketplace',build:'46-neon-persistent-marketplace',database:{ok:false,error:e.message},storage:{configured:neonStorage.configured}})}});
app.use('/api/listings',require('./src/routes/listings'));
app.use('/api/marketplace-live',require('./src/routes/marketplaceLive'));
app.use('/api/marketplace-settings',require('./src/routes/marketplaceSettings'));
app.use('/api/admin/sellers',require('./src/routes/adminSellers'));
app.use('/api/seller',require('./src/routes/seller'));
app.use(express.static(__dirname,{extensions:['html']}));
app.use((err,req,res,next)=>{console.error(err);res.status(err.status||500).json({error:err.message||'Server error'})});
app.listen(config.port,'0.0.0.0',()=>console.log('TCS Marketplace Neon API listening on port '+config.port));
