const express=require('express');
const config=require('./src/config');
const {parseCookies,setSecurityHeaders,rateLimit}=require('./src/security');
const {initDb,health:dbHealth,closeDb}=require('./src/db');
const fs=require('fs');
[config.uploadDir,config.listingImageDir,config.backupDir].forEach(d=>fs.mkdirSync(d,{recursive:true}));
const app=express();
const allowedOrigins=new Set(['https://marketplace.tcstowing.co.za','https://www.marketplace.tcstowing.co.za','https://marketplace.wykiesautomation.co.za','https://www.marketplace.wykiesautomation.co.za','http://localhost:3000']);
app.use((req,res,next)=>{const origin=req.headers.origin;if(origin&&allowedOrigins.has(origin)){res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Headers','Content-Type,X-Demo-User');res.setHeader('Access-Control-Allow-Methods','GET,POST,PATCH,DELETE,OPTIONS')}if(req.method==='OPTIONS')return res.sendStatus(204);next()});
app.set('trust proxy',1);
app.use(parseCookies);app.use(setSecurityHeaders);app.use(rateLimit());
app.use(express.json({limit:'2mb'}));app.use(express.urlencoded({extended:true}));
app.get('/api/health',async(req,res)=>{try{res.json({ok:true,service:'tcs-marketplace',build:'47-neon-ready',database:await dbHealth()})}catch(e){res.status(503).json({ok:false,error:e.message})}});
app.use('/api/listings',require('./src/routes/listings'));
app.use('/api/marketplace-settings',require('./src/routes/marketplaceSettings'));
app.use('/api/marketplace-live',require('./src/routes/marketplaceLive'));
app.use('/api/admin/sellers',require('./src/routes/adminSellers'));
app.use('/api/seller',require('./src/routes/seller'));
app.use('/listing-images',express.static(config.listingImageDir,{maxAge:'7d'}));
app.use(express.static(__dirname,{extensions:['html']}));
let server;async function start(){await initDb();server=app.listen(config.port,'0.0.0.0',()=>console.log('TCS Marketplace listening on port '+config.port))}start().catch(e=>{console.error('Startup failed:',e);process.exit(1)});async function shutdown(){if(server)server.close();await closeDb();process.exit(0)}process.on('SIGTERM',shutdown);process.on('SIGINT',shutdown);module.exports=app;
