const r=require('express').Router();
const {requireRole}=require('../auth');
const db=require('../neonDb');
function clean(v,n=1000){return String(v||'').trim().slice(0,n)}
function id(prefix){return prefix+'_'+Date.now()+'_'+Math.random().toString(36).slice(2,8)}
function asyncRoute(fn){return(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next)}
function emailOk(v){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v||''))}
function normalizeWhatsApp(v){let n=String(v||'').replace(/\D/g,'');if(n.startsWith('0')&&n.length===10)n='27'+n.slice(1);return n.startsWith('27')&&n.length===11?n:''}
r.get('/public/contact/:id',asyncRoute(async(req,res)=>{const x=await db.query("select * from marketplace_listings where (id=$1 or slug=$1) and status='active' and approval_status='approved' limit 1",[req.params.id]);const v=x.rows[0];if(!v)return res.status(404).json({error:'Advert not found'});res.json({listingId:v.id,title:v.title,phone:v.phone||'',whatsapp:normalizeWhatsApp(v.whatsapp),emailAvailable:true})}));
r.post('/public/contact/:id/email',asyncRoute(async(req,res)=>{const x=await db.query("select * from marketplace_listings where (id=$1 or slug=$1) and status='active' and approval_status='approved' limit 1",[req.params.id]);const v=x.rows[0];if(!v)return res.status(404).json({error:'Advert not found'});const name=clean(req.body.name,80),email=clean(req.body.email,160),message=clean(req.body.message,2000);if(!name||!emailOk(email)||message.length<10)return res.status(400).json({error:'Enter your name, valid email and a proper message'});const msgId=id('msg');await db.query('insert into marketplace_messages(id,listing_id,seller_id,buyer_name,buyer_email,message,status) values($1,$2,$3,$4,$5,$6,\'new\')',[msgId,v.id,v.seller_id,name,email,message]);res.json({ok:true,reference:msgId})}));
r.post('/public/report/:id',asyncRoute(async(req,res)=>{const reportId=id('report'),reason=clean(req.body.reason,500);if(reason.length<5)return res.status(400).json({error:'Please provide a report reason'});await db.query('insert into marketplace_reports(id,listing_id,reason,email,status) values($1,$2,$3,$4,\'open\')',[reportId,req.params.id,reason,clean(req.body.email,160)]);res.json({ok:true,reference:reportId})}));
r.get('/admin/reports',requireRole('admin'),asyncRoute(async(req,res)=>{const x=await db.query('select id,listing_id as "listingId",reason,email,status,created_at as "createdAt" from marketplace_reports order by created_at desc');res.json(x.rows)}));
r.get('/admin/messages',requireRole('admin'),asyncRoute(async(req,res)=>{const x=await db.query('select id,listing_id as "listingId",seller_id as "sellerId",buyer_name as "buyerName",buyer_email as "buyerEmail",message,status,created_at as "createdAt" from marketplace_messages order by created_at desc');res.json(x.rows)}));
r.post('/admin/listing/:id/action',requireRole('admin'),asyncRoute(async(req,res)=>{const action=clean(req.body.action,30);let sql;if(action==='suspend')sql="update marketplace_listings set status='suspended',updated_at=now() where id=$1 returning *";else if(action==='activate')sql="update marketplace_listings set status='active',approval_status='approved',updated_at=now() where id=$1 returning *";else return res.status(400).json({error:'Invalid action'});const x=await db.query(sql,[req.params.id]);if(!x.rows[0])return res.status(404).json({error:'Advert not found'});res.json({ok:true})}));
r.get('/public/seo/listings',asyncRoute(async(req,res)=>{const x=await db.query("select slug,coalesce(updated_at,approved_at,created_at) as updated from marketplace_listings where status='active' and approval_status='approved'");res.json(x.rows)}));
module.exports=r;
